# =========================================================================
# 📁 CONFIGURATION SERVEUR sFTP (CHOMIAMOS)
# Ce fichier est géré automatiquement par le Dashboard ChomiamOS.
# =========================================================================

# Règles globales de sécurité pour le groupe sftp-users
Match Group sftp-users
    PasswordAuthentication yes
    KbdInteractiveAuthentication yes
    PermitEmptyPasswords no
    X11Forwarding no
    AllowTcpForwarding no
    PermitTunnel no

# Utilisateur sFTP: fanfan (Dossier: /home/chomiam/Partages/sftp_public, Permissions: rw)
Match User fanfan
    PasswordAuthentication yes
    KbdInteractiveAuthentication yes
    X11Forwarding no
    AllowTcpForwarding no
    PermitTunnel no
    ForceCommand internal-sftp -P remove,rmdir -d /home/chomiam/Partages/sftp_public

