# =========================================================================
# 📁 CONFIGURATION SERVEUR sFTP (CHOMIAMOS)
# Ce fichier est géré automatiquement par l'espace Réseau du Dashboard.
# =========================================================================

# Règles globales pour les utilisateurs sFTP isolés
Match Group sftp-users
    PasswordAuthentication yes
    KbdInteractiveAuthentication yes
    PermitEmptyPasswords no
    X11Forwarding no
    AllowTcpForwarding no
    PermitTunnel no
